/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tecsus.ddc.view.frames.energy;

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.border.*;
import javax.swing.table.*;
import com.tecsus.ddc.bills.energy.EnergyBill;
import com.tecsus.ddc.view.frames.generator.EnergyBillGenerator;
import com.tecsus.ddc.controller.service.EnergyBillService;
import com.tecsus.ddc.view.frames.home.TelaHome;


/**
 *
 * @author William Antoniazzi
 */
public class Energia extends javax.swing.JInternalFrame {
//    private EnergyBillController controller;
    private EnergyBillFormTextFields fields;
    private final EnergyBillService energyBillService;
    //private EnergyBillFormLabelsFields labels;

    /**
     * Creates new form Energia
     */
    public Energia(final EnergyBillService energyBillService) {
        fields = new EnergyBillFormTextFields();
        this.energyBillService = energyBillService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - William Antoniazzi
    private void initComponents() {
        ScrPanelEnergia = new JScrollPane();
        PanelEnergia = new JPanel();
        PanelClienteLocal = new JPanel();
        lblCpfCnpj = new JLabel();
//        txtCpfCnpj = new JTextField();
        lblInsEstadual = new JLabel();
//        txtInsEstadual = new JTextField();
        lblRazaoSocial = new JLabel();
//        txtRazaoSocial = new JTextField();
        lblNomeCliente = new JLabel();
//        txtNomeClienteEnd = new JTextField();
        lblVazio01 = new JLabel();
        lblEndereco = new JLabel();
//        txtEndereco = new JTextField();
        lblNumero = new JLabel();
//        txtNumeroEnd = new JTextField();
        lblComplemento = new JLabel();
//        txtComplementoEnd = new JTextField();
        lblBairro = new JLabel();
//        txtBairroEnd = new JTextField();
        lblCidadeEnd = new JLabel();
//        txtCidadeEnd = new JTextField();
        lblCepEnd = new JLabel();
//        txtCepEnd = new JTextField();
        lblEstadoEnd = new JLabel();
        cbxEstadoEnd = new JComboBox<>();
        lblVazio02 = new JLabel();
        lblCodIdentificacao = new JLabel();
//        txtCodIdentificacao = new JTextField();
        lblCodFiscalOperacao = new JLabel();
//        txtCodFiscalOperacao = new JTextField();
        lblGrupo = new JLabel();
//        txtGrupo = new JTextField();
        lblSubgrupo = new JLabel();
//        txtSubgrupo = new JTextField();
        lblClasse = new JLabel();
//        txtClasse = new JTextField();
        lblTipoFornecimento = new JLabel();
//        txtTipoFornecimento = new JTextField();
        lblModalidadeTarifa = new JLabel();
//        txtModalidadeTarifa = new JTextField();
        lblRoteiroLeitura = new JLabel();
//        txtRoteiroLeitura = new JTextField();
        lblTensaoNominal = new JLabel();
//        txtTensaoNominal = new JTextField();
        lblNumeroMedidor = new JLabel();
//        txtNumeroMedidor = new JTextField();
        lblNumeroInstalacao = new JLabel();
//        txtNumeroInstalacao = new JTextField();
        lblSubclasse = new JLabel();
//        txtSubclasse = new JTextField();
        PanelBandDadosPeriodo = new JPanel();
        lblDataVencimento = new JLabel();
//        txtDataVencimento = new JTextField();
        lblContaMes = new JLabel();
//        txtContaMes = new JTextField();
        lblValorTotalPagar = new JLabel();
//        txtValorTotalPagar = new JTextField();
        lblConsumoKwhMes = new JLabel();
//        txtConsumoKwhMes = new JTextField();
        lblDataInicioBandeira = new JLabel();
//        txtDataInicioBandeira = new JTextField();
        lblDataFinalBandeira = new JLabel();
//        txtDataFinalBandeira = new JTextField();
        lblTipoBandeira = new JLabel();
//        txtTipoBandeira = new JTextField();
        PanelFaturamento = new JPanel();
        lblEmissaoFatura = new JLabel();
//        txtEmissaoFatura = new JTextField();
        lblDiasFatura = new JLabel();
//        txtDiasFatura = new JTextField();
        lblDataLeitAnterior = new JLabel();
//        txtDataLeitAnterior = new JTextField();
        lblDataLeitAtual = new JLabel();
//        txtDataLeitAtual = new JTextField();
        lblDataLeitProxima = new JLabel();
//        txtDataLeitProxima = new JTextField();
        lblLeituraAntKwh = new JLabel();
//        txtLeituraAntKwh = new JTextField();
        lblLeituraAtualKwh = new JLabel();
//        txtLeituraAtualKwh = new JTextField();
        jScrollPane1 = new JScrollPane();
        tblFaturamento = new JTable();
        lblDescricaoFatura = new JLabel();
        cbxDescicaoFatura = new JComboBox<>();
        lblValorFornecido = new JLabel();
//        txtValorFornecido = new JTextField();
        lblValorTotalFatura = new JLabel();
//        txtValorTotalFatura = new JTextField();
        bntAdd = new JButton();
        bntDelete = new JButton();
        lblItensFinanceiros = new JLabel();
        lblCIPMunicipal = new JLabel();
//        txtCIPMunicipal = new JTextField();
        lblTributos = new JLabel();
        lblPIS = new JLabel();
//        txtValorPIS = new JTextField();
        lblCofins = new JLabel();
//        txtValorCofins = new JTextField();
        lblICMS = new JLabel();
//        txtValorICMS = new JTextField();
        btnVoltar = new JButton();
        btnLimpar = new JButton();
        btnSalvar = new JButton();

        //======== this ========
        setTitle("DDC - Sistema de Digita\u00e7\u00e3o de Contas");
        setToolTipText("");
        setName("");
        Container contentPane = getContentPane();

        //======== ScrPanelEnergia ========
        {
            ScrPanelEnergia.setToolTipText("");
            ScrPanelEnergia.setColumnHeaderView(null);
            ScrPanelEnergia.setRowHeaderView(null);

            //======== PanelEnergia ========
            {
                PanelEnergia.setBorder(new TitledBorder("CADASTRO DE CONTA DE ENERGIA"));
                PanelEnergia.setToolTipText("");
                PanelEnergia.setName("");
                PanelEnergia.setOpaque(false);
                PanelEnergia.setBorder ( new javax . swing. border .CompoundBorder ( new javax . swing. border .TitledBorder ( new javax . swing.
                border .EmptyBorder ( 0, 0 ,0 , 0) ,  "JF\u006frmDes\u0069gner \u0045valua\u0074ion" , javax. swing .border . TitledBorder. CENTER
                ,javax . swing. border .TitledBorder . BOTTOM, new java. awt .Font ( "D\u0069alog", java .awt . Font
                . BOLD ,12 ) ,java . awt. Color .red ) ,PanelEnergia. getBorder () ) ); PanelEnergia. addPropertyChangeListener(
                new java. beans .PropertyChangeListener ( ){ @Override public void propertyChange (java . beans. PropertyChangeEvent e) { if( "\u0062order"
                .equals ( e. getPropertyName () ) )throw new RuntimeException( ) ;} } );

                //======== PanelClienteLocal ========
                {
                    PanelClienteLocal.setBorder(new TitledBorder(null, "CLIENTE / LOCAL CONSUMO", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION));

                    //---- lblCpfCnpj ----
                    lblCpfCnpj.setText("CPF/ CNPJ/ CI:");

                    //---- txtCpfCnpj ----
                    fields.getTxtCpfCnpj().setHorizontalAlignment(JTextField.LEFT);
                    fields.getTxtCpfCnpj().setToolTipText("");

                    //---- lblInsEstadual ----
                    lblInsEstadual.setText("Inscri\u00e7\u00e3o Estadual:");

                    //---- lblRazaoSocial ----
                    lblRazaoSocial.setText("Raz\u00e3o Social: ");
                    lblRazaoSocial.setToolTipText("");

                    //---- txtRazaoSocial ----
                    fields.getTxtRazaoSocial().setScrollOffset(1);

                    //---- lblNomeCliente ----
                    lblNomeCliente.setText("Nome Cliente:");

                    //---- lblVazio01 ----
                    lblVazio01.setText("   ");

                    //---- lblEndereco ----
                    lblEndereco.setText("Endere\u00e7o (Rua, Avenida, Estrada...):");

                    //---- lblNumero ----
                    lblNumero.setText("N\u00famero:");

                    //---- txtNumeroEnd ----
                    fields.getTxtNumeroEnd().setToolTipText("");

                    //---- lblComplemento ----
                    lblComplemento.setText("Complemento:");

                    //---- txtComplementoEnd ----
                    fields.getTxtComplementoEnd().setToolTipText("");

                    //---- lblBairro ----
                    lblBairro.setText("Bairro: ");

                    //---- txtBairroEnd ----
                    fields.getTxtBairroEnd().setToolTipText("");

                    //---- lblCidadeEnd ----
                    lblCidadeEnd.setText("Cidade:");

                    //---- txtCidadeEnd ----
                    fields.getTxtCidadeEnd().setToolTipText("");

                    //---- lblCepEnd ----
                    lblCepEnd.setText("CEP:");

                    //---- txtCepEnd ----
                    fields.getTxtCepEnd().setToolTipText("");

                    //---- lblEstadoEnd ----
                    lblEstadoEnd.setText("Estado:");

                    //---- cbxEstadoEnd ----
                    cbxEstadoEnd.setModel(new DefaultComboBoxModel<>(new String[] {
                        "Item 1",
                        "Item 2",
                        "Item 3",
                        "Item 4"
                    }));

                    //---- lblVazio02 ----
                    lblVazio02.setText("   ");

                    //---- lblCodIdentificacao ----
                    lblCodIdentificacao.setText("N\u00famero da Conta:");

                    //---- lblCodFiscalOperacao ----
                    lblCodFiscalOperacao.setText("Cod. Fiscal Opera\u00e7\u00e3o:");

                    //---- txtCodFiscalOperacao ----
                    fields.getTxtCodFiscalOperacao().setToolTipText("");

                    //---- lblGrupo ----
                    lblGrupo.setText("Grupo:");
                    lblGrupo.setToolTipText("");

                    //---- txtGrupo ----
                    fields.getTxtGrupo().setToolTipText("");

                    //---- lblSubgrupo ----
                    lblSubgrupo.setText("Subgrupo:");
                    lblSubgrupo.setToolTipText("");

                    //---- txtSubgrupo ----
                    fields.getTxtSubgrupo().setToolTipText("");

                    //---- lblClasse ----
                    lblClasse.setText("Classe:");

                    //---- lblTipoFornecimento ----
                    lblTipoFornecimento.setText("Tipo Fornecimento:");

                    //---- lblModalidadeTarifa ----
                    lblModalidadeTarifa.setText("Modalidade Tarifa:");

                    //---- lblRoteiroLeitura ----
                    lblRoteiroLeitura.setText("Roteiro de Leitura:");

                    //---- lblTensaoNominal ----
                    lblTensaoNominal.setText("Tens\u00e3o Nominal:");

                    //---- txtTensaoNominal ----
                    fields.getTxtTensaoNominal().setToolTipText("");

                    //---- lblNumeroMedidor ----
                    lblNumeroMedidor.setText("N\u00famero Medidor:");

                    //---- lblNumeroInstalacao ----
                    lblNumeroInstalacao.setText("N\u00famero da Instala\u00e7\u00e3o:");

                    //---- txtNumeroInstalacao ----
                    fields.getTxtNumeroInstalacao().setToolTipText("");

                    //---- lblSubclasse ----
                    lblSubclasse.setText("Subclase:");

                    GroupLayout PanelClienteLocalLayout = new GroupLayout(PanelClienteLocal);
                    PanelClienteLocal.setLayout(PanelClienteLocalLayout);
                    PanelClienteLocalLayout.setHorizontalGroup(
                        PanelClienteLocalLayout.createParallelGroup()
                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                .addGroup(PanelClienteLocalLayout.createParallelGroup()
                                    .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                        .addGroup(PanelClienteLocalLayout.createParallelGroup()
                                            .addComponent(lblCodIdentificacao)
                                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(lblVazio02)))
                                        .addGap(14, 14, 14)
                                        .addComponent(fields.getTxtCodIdentificacao(), GroupLayout.PREFERRED_SIZE, 100,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCodFiscalOperacao)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtCodFiscalOperacao(), GroupLayout.PREFERRED_SIZE, 60,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblGrupo)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtGrupo(), GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblSubgrupo)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtSubgrupo(), GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblClasse)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtClasse(), GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                        .addGroup(PanelClienteLocalLayout.createParallelGroup()
                                            .addComponent(lblCpfCnpj)
                                            .addComponent(lblInsEstadual)
                                            .addComponent(lblVazio01))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelClienteLocalLayout.createParallelGroup()
                                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                                .addComponent(fields.getTxtInsEstadual(), GroupLayout.PREFERRED_SIZE, 100,
                                                        GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblNomeCliente)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fields.getTxtNomeClienteEnd()))
                                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                                .addComponent(fields.getTxtCpfCnpj(), GroupLayout.PREFERRED_SIZE, 100,
                                                        GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblRazaoSocial)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fields.getTxtRazaoSocial()))))
                                    .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                        .addComponent(lblEndereco)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtEndereco()))
                                    .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                        .addGroup(PanelClienteLocalLayout.createParallelGroup()
                                            .addComponent(lblNumero)
                                            .addComponent(lblCidadeEnd))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelClienteLocalLayout.createParallelGroup()
                                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                                .addComponent(fields.getTxtCidadeEnd(), GroupLayout.PREFERRED_SIZE, 370,
                                                        GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblCepEnd)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fields.getTxtCepEnd(), GroupLayout.PREFERRED_SIZE, 80,
                                                        GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblEstadoEnd)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbxEstadoEnd))
                                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                                .addComponent(fields.getTxtNumeroEnd(), GroupLayout.PREFERRED_SIZE, 80,
                                                        GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblComplemento)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fields.getTxtComplementoEnd(), GroupLayout.PREFERRED_SIZE, 80,
                                                        GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblBairro)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fields.getTxtBairroEnd())))))
                                .addGap(21, 21, 21))
                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                .addGroup(PanelClienteLocalLayout.createParallelGroup()
                                    .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                        .addComponent(lblSubclasse)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtSubclasse(), GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTipoFornecimento)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtTipoFornecimento(), GroupLayout.PREFERRED_SIZE, 85,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblModalidadeTarifa)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtModalidadeTarifa(), GroupLayout.PREFERRED_SIZE, 90,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblRoteiroLeitura)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtRoteiroLeitura(), GroupLayout.PREFERRED_SIZE, 100,
                                                GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                        .addComponent(lblNumeroMedidor)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtNumeroMedidor(), GroupLayout.PREFERRED_SIZE, 100,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblNumeroInstalacao)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtNumeroInstalacao(), GroupLayout.PREFERRED_SIZE, 100,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTensaoNominal)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtTensaoNominal(), GroupLayout.PREFERRED_SIZE, 69,
                                                GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );
                    PanelClienteLocalLayout.setVerticalGroup(
                        PanelClienteLocalLayout.createParallelGroup()
                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                .addGroup(PanelClienteLocalLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCpfCnpj)
                                    .addComponent(fields.getTxtCpfCnpj(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRazaoSocial)
                                    .addComponent(fields.getTxtRazaoSocial(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelClienteLocalLayout.createParallelGroup()
                                    .addComponent(lblInsEstadual, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelClienteLocalLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblNomeCliente)
                                        .addComponent(fields.getTxtNomeClienteEnd(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fields.getTxtInsEstadual(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVazio01)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelClienteLocalLayout.createParallelGroup()
                                    .addComponent(lblEndereco)
                                    .addComponent(fields.getTxtEndereco(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelClienteLocalLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNumero)
                                    .addComponent(fields.getTxtNumeroEnd(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblComplemento)
                                    .addComponent(fields.getTxtComplementoEnd(), GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBairro)
                                    .addComponent(fields.getTxtBairroEnd(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelClienteLocalLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCidadeEnd)
                                    .addComponent(lblCepEnd)
                                    .addComponent(lblEstadoEnd)
                                    .addComponent(fields.getTxtCidadeEnd(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fields.getTxtCepEnd(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxEstadoEnd, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVazio02)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelClienteLocalLayout.createParallelGroup()
                                    .addComponent(fields.getTxtCodIdentificacao(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodIdentificacao)
                                    .addComponent(fields.getTxtCodFiscalOperacao(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodFiscalOperacao)
                                    .addGroup(PanelClienteLocalLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(fields.getTxtGrupo(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblGrupo)
                                        .addComponent(fields.getTxtSubgrupo(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblSubgrupo)
                                        .addComponent(lblClasse)
                                        .addComponent(fields.getTxtClasse(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelClienteLocalLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSubclasse)
                                    .addComponent(fields.getTxtSubclasse(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTipoFornecimento)
                                    .addComponent(fields.getTxtTipoFornecimento(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblModalidadeTarifa)
                                    .addComponent(fields.getTxtModalidadeTarifa(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRoteiroLeitura)
                                    .addComponent(fields.getTxtRoteiroLeitura(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelClienteLocalLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNumeroMedidor)
                                    .addComponent(fields.getTxtNumeroMedidor(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNumeroInstalacao)
                                    .addComponent(fields.getTxtNumeroInstalacao(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTensaoNominal)
                                    .addComponent(fields.getTxtTensaoNominal(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)))
                    );
                }

                //======== PanelBandDadosPeriodo ========
                {
                    PanelBandDadosPeriodo.setBorder(new TitledBorder(null, "BANDEIRA / DADOS CONTA / PER\u00cdODO E DESCRI\u00c7\u00c3O CONSUMO", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION));

                    //---- lblDataVencimento ----
                    lblDataVencimento.setText("Data Vencimento:");

                    //---- txtDataVencimento ----
                    fields.getTxtDataVencimento().setToolTipText("");

                    //---- lblContaMes ----
                    lblContaMes.setText("Conta M\u00eas:");

                    //---- lblValorTotalPagar ----
                    lblValorTotalPagar.setText("Valor Total Pagar:");

                    //---- txtValorTotalPagar ----
                    fields.getTxtValorTotalPagar().setToolTipText("");

                    //---- lblConsumoKwhMes ----
                    lblConsumoKwhMes.setText("Consumo kWh M\u00eas:");

                    //---- lblDataInicioBandeira ----
                    lblDataInicioBandeira.setText("Data In\u00edcio Bandeira:");

                    //---- lblDataFinalBandeira ----
                    lblDataFinalBandeira.setText("Data Final Bandeira:");

                    //---- lblTipoBandeira ----
                    lblTipoBandeira.setText("Tipo Bandeira:");

                    GroupLayout PanelBandDadosPeriodoLayout = new GroupLayout(PanelBandDadosPeriodo);
                    PanelBandDadosPeriodo.setLayout(PanelBandDadosPeriodoLayout);
                    PanelBandDadosPeriodoLayout.setHorizontalGroup(
                        PanelBandDadosPeriodoLayout.createParallelGroup()
                            .addGroup(PanelBandDadosPeriodoLayout.createSequentialGroup()
                                .addComponent(lblDataVencimento)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fields.getTxtDataVencimento(), GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblContaMes)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fields.getTxtContaMes(), GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValorTotalPagar)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fields.getTxtValorTotalPagar(), GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblConsumoKwhMes)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fields.getTxtConsumoKwhMes())
                                .addGap(10, 10, 10))
                            .addGroup(PanelBandDadosPeriodoLayout.createSequentialGroup()
                                .addComponent(lblDataInicioBandeira)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fields.getTxtDataInicioBandeira(), GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDataFinalBandeira)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fields.getTxtDataFinalBandeira(), GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTipoBandeira)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fields.getTxtTipoBandeira(), GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );
                    PanelBandDadosPeriodoLayout.setVerticalGroup(
                        PanelBandDadosPeriodoLayout.createParallelGroup()
                            .addGroup(PanelBandDadosPeriodoLayout.createSequentialGroup()
                                .addGroup(PanelBandDadosPeriodoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDataVencimento)
                                    .addComponent(fields.getTxtDataVencimento(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblContaMes)
                                    .addComponent(fields.getTxtContaMes(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValorTotalPagar)
                                    .addComponent(fields.getTxtValorTotalPagar(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblConsumoKwhMes)
                                    .addComponent(fields.getTxtConsumoKwhMes(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelBandDadosPeriodoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDataInicioBandeira)
                                    .addComponent(fields.getTxtDataInicioBandeira(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataFinalBandeira)
                                    .addComponent(fields.getTxtDataFinalBandeira(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTipoBandeira)
                                    .addComponent(fields.getTxtTipoBandeira(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                    );
                }

                //======== PanelFaturamento ========
                {
                    PanelFaturamento.setBorder(new TitledBorder(null, "DETALHES FATURAMENTO", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION));

                    //---- lblEmissaoFatura ----
                    lblEmissaoFatura.setText("Emiss\u00e3o Fatura:");

                    //---- lblDiasFatura ----
                    lblDiasFatura.setText("Dias de Faturamento:");

                    //---- lblDataLeitAnterior ----
                    lblDataLeitAnterior.setText("Data Leitura Anterior:");

                    //---- lblDataLeitAtual ----
                    lblDataLeitAtual.setText("Data Leitura Atual:");

                    //---- lblDataLeitProxima ----
                    lblDataLeitProxima.setText("Data Leitura Pr\u00f3xima:");

                    //---- lblLeituraAntKwh ----
                    lblLeituraAntKwh.setText("Leitura Anterior kWh:");

                    //---- lblLeituraAtualKwh ----
                    lblLeituraAtualKwh.setText("Leitura Atual kWh:");

                    //======== jScrollPane1 ========
                    {

                        //---- tblFaturamento ----
                        tblFaturamento.setModel(new DefaultTableModel(
                            new Object[][] {
                            },
                            new String[] {
                                "Descri\u00e7\u00e3o", "Valor Fornecido", "Valor Total"
                            }
                        ));
                        jScrollPane1.setViewportView(tblFaturamento);
                    }

                    //---- lblDescricaoFatura ----
                    lblDescricaoFatura.setText("Descri\u00e7\u00e3o:");

                    //---- cbxDescicaoFatura ----
                    cbxDescicaoFatura.setModel(new DefaultComboBoxModel<>(new String[] {
                        "Item 1",
                        "Item 2",
                        "Item 3",
                        "Item 4"
                    }));

                    //---- lblValorFornecido ----
                    lblValorFornecido.setText("Valor Fornecido:");

                    //---- lblValorTotalFatura ----
                    lblValorTotalFatura.setText("Valor Total:");

                    //---- bntAdd ----
                    bntAdd.setText("Adicionar");
                    bntAdd.addActionListener(e -> bntAddActionPerformed(e));

                    //---- bntDelete ----
                    bntDelete.setText("Remover");
                    bntDelete.addActionListener(e -> bntDeleteActionPerformed(e));

                    //---- lblItensFinanceiros ----
                    lblItensFinanceiros.setText("Itens Financeiros:");

                    //---- lblCIPMunicipal ----
                    lblCIPMunicipal.setText("CIP - Contribui\u00e7\u00e3o Municipal:");

                    //---- lblTributos ----
                    lblTributos.setText("Tributos:");

                    //---- lblPIS ----
                    lblPIS.setText("PIS:");

                    //---- lblCofins ----
                    lblCofins.setText("COFINS:");

                    //---- lblICMS ----
                    lblICMS.setText("ICMS:");

                    GroupLayout PanelFaturamentoLayout = new GroupLayout(PanelFaturamento);
                    PanelFaturamento.setLayout(PanelFaturamentoLayout);
                    PanelFaturamentoLayout.setHorizontalGroup(
                        PanelFaturamentoLayout.createParallelGroup()
                            .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                .addGroup(PanelFaturamentoLayout.createParallelGroup()
                                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                        .addComponent(lblEmissaoFatura)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtEmissaoFatura(), GroupLayout.PREFERRED_SIZE, 70,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDiasFatura)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtDiasFatura(), GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDataLeitAnterior)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtDataLeitAnterior(), GroupLayout.PREFERRED_SIZE, 70,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDataLeitAtual)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtDataLeitAtual(), GroupLayout.PREFERRED_SIZE, 70,
                                                GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                        .addComponent(lblDataLeitProxima)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtDataLeitProxima(), GroupLayout.PREFERRED_SIZE, 70,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblLeituraAntKwh)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtLeituraAntKwh(), GroupLayout.PREFERRED_SIZE, 100,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblLeituraAtualKwh)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtLeituraAtualKwh(), GroupLayout.PREFERRED_SIZE, 100,
                                                GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                        .addComponent(lblTributos)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPIS)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtValorPIS(), GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCofins)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtValorCofins(), GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblICMS)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtValorICMS(), GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                        .addComponent(lblItensFinanceiros)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCIPMunicipal)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fields.getTxtCIPMunicipal(), GroupLayout.PREFERRED_SIZE, 70,
                                                GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                        .addGroup(PanelFaturamentoLayout.createParallelGroup()
                                            .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                                .addComponent(lblDescricaoFatura)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbxDescicaoFatura, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                                .addComponent(lblValorFornecido)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fields.getTxtValorFornecido(), GroupLayout.PREFERRED_SIZE, 120,
                                                        GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                                .addComponent(lblValorTotalFatura)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(PanelFaturamentoLayout.createParallelGroup()
                                                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                                        .addComponent(bntAdd)
                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(bntDelete))
                                                    .addComponent(fields.getTxtValorTotalFatur(a, GroupLayout.PREFERRED_SIZE, 120,
                                                            GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 501, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );
                    PanelFaturamentoLayout.setVerticalGroup(
                        PanelFaturamentoLayout.createParallelGroup()
                            .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                .addGroup(PanelFaturamentoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmissaoFatura)
                                    .addComponent(fields.getTxtEmissaoFatura(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDiasFatura)
                                    .addComponent(fields.getTxtDiasFatura(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataLeitAnterior)
                                    .addComponent(fields.getTxtDataLeitAnterior(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataLeitAtual)
                                    .addComponent(fields.getTxtDataLeitAtual(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelFaturamentoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDataLeitProxima)
                                    .addComponent(fields.getTxtDataLeitProxima(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLeituraAntKwh)
                                    .addComponent(fields.getTxtLeituraAntKwh(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLeituraAtualKwh)
                                    .addComponent(fields.getTxtLeituraAtualKwh(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanelFaturamentoLayout.createParallelGroup()
                                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(PanelFaturamentoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblDescricaoFatura)
                                            .addComponent(cbxDescicaoFatura, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelFaturamentoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblValorFornecido)
                                            .addComponent(fields.getTxtValorFornecido(), GroupLayout.PREFERRED_SIZE,
                                                    GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelFaturamentoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblValorTotalFatura)
                                            .addComponent(fields.getTxtValorTotalFatura(), GroupLayout.PREFERRED_SIZE,
                                                    GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanelFaturamentoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(bntAdd)
                                            .addComponent(bntDelete)))
                                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelFaturamentoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCIPMunicipal)
                                    .addComponent(fields.getTxtCIPMunicipal(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItensFinanceiros))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelFaturamentoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPIS)
                                    .addComponent(fields.getTxtValorPIS(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTributos)
                                    .addComponent(lblCofins)
                                    .addComponent(fields.getTxtValorCofins(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblICMS)
                                    .addComponent(fields.getTxtValorICMS(), GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                            GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );
                }

                //---- btnVoltar ----
                btnVoltar.setText("Voltar");
                btnVoltar.addActionListener(e -> btnVoltarActionPerformed(e));

                //---- btnLimpar ----
                btnLimpar.setText("Limpar");

                //---- btnSalvar ----
                btnSalvar.setText("Salvar");
                btnSalvar.addActionListener(e -> btnSalvarActionPerformed(e));

                GroupLayout PanelEnergiaLayout = new GroupLayout(PanelEnergia);
                PanelEnergia.setLayout(PanelEnergiaLayout);
                PanelEnergiaLayout.setHorizontalGroup(
                    PanelEnergiaLayout.createParallelGroup()
                        .addGroup(PanelEnergiaLayout.createSequentialGroup()
                            .addGroup(PanelEnergiaLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PanelBandDadosPeriodo, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PanelClienteLocal, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PanelFaturamento, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(GroupLayout.Alignment.TRAILING, PanelEnergiaLayout.createSequentialGroup()
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalvar, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLimpar, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnVoltar, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29))
                );
                PanelEnergiaLayout.setVerticalGroup(
                    PanelEnergiaLayout.createParallelGroup()
                        .addGroup(PanelEnergiaLayout.createSequentialGroup()
                            .addComponent(PanelClienteLocal, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(PanelBandDadosPeriodo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(PanelFaturamento, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(PanelEnergiaLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(btnVoltar)
                                .addComponent(btnLimpar)
                                .addComponent(btnSalvar))
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
            }
            ScrPanelEnergia.setViewportView(PanelEnergia);
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(ScrPanelEnergia, GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addComponent(ScrPanelEnergia, GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       controller.pushBill(EnergyBillGenerator.generate(fields));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void bntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddActionPerformed
        // TODO add your handling code here:
      	//String descricao = cbxDescicaoFatura.getText().trim(); // jtxxx e o nome do campo fields.getTxt no formulário.
	String valorFornecido = fields.getTxtValorTotalFatura().getText().trim();
        String valorTotal = fields.getTxtValorTotalPagar().getText().trim();
	
	DefaultTableModel val = (DefaultTableModel) tblFaturamento.getModel();
		val.addRow(new String[]{valorFornecido, valorTotal});
		//cbxDescicaoFatura.setText("");
		fields.getTxtValorTotalFatura().setText("");
		fields.getTxtValorTotalPagar().setText("");
		
		cbxDescicaoFatura.requestFocus();
    }//GEN-LAST:event_bntAddActionPerformed

    private void bntDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDeleteActionPerformed
        // TODO add your handling code here:
        ((DefaultTableModel) tblFaturamento.getModel()).removeRow(tblFaturamento.getSelectedRow());
		cbxDescicaoFatura.requestFocus();
    }//GEN-LAST:event_bntDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - William Antoniazzi
    private JScrollPane ScrPanelEnergia;
    private JPanel PanelEnergia;
    private JPanel PanelClienteLocal;
    private JLabel lblCpfCnpj;
    private JTextField txtCpfCnpj;
    private JLabel lblInsEstadual;
    private JTextField txtInsEstadual;
    private JLabel lblRazaoSocial;
    private JTextField txtRazaoSocial;
    private JLabel lblNomeCliente;
    private JTextField txtNomeClienteEnd;
    private JLabel lblVazio01;
    private JLabel lblEndereco;
    private JTextField txtEndereco;
    private JLabel lblNumero;
    private JTextField txtNumeroEnd;
    private JLabel lblComplemento;
    private JTextField txtComplementoEnd;
    private JLabel lblBairro;
    private JTextField txtBairroEnd;
    private JLabel lblCidadeEnd;
    private JTextField txtCidadeEnd;
    private JLabel lblCepEnd;
    private JTextField txtCepEnd;
    private JLabel lblEstadoEnd;
    private JComboBox<String> cbxEstadoEnd;
    private JLabel lblVazio02;
    private JLabel lblCodIdentificacao;
    private JTextField txtCodIdentificacao;
    private JLabel lblCodFiscalOperacao;
    private JTextField txtCodFiscalOperacao;
    private JLabel lblGrupo;
    private JTextField txtGrupo;
    private JLabel lblSubgrupo;
    private JTextField txtSubgrupo;
    private JLabel lblClasse;
    private JTextField txtClasse;
    private JLabel lblTipoFornecimento;
    private JTextField txtTipoFornecimento;
    private JLabel lblModalidadeTarifa;
    private JTextField txtModalidadeTarifa;
    private JLabel lblRoteiroLeitura;
    private JTextField txtRoteiroLeitura;
    private JLabel lblTensaoNominal;
    private JTextField txtTensaoNominal;
    private JLabel lblNumeroMedidor;
    private JTextField txtNumeroMedidor;
    private JLabel lblNumeroInstalacao;
    private JTextField txtNumeroInstalacao;
    private JLabel lblSubclasse;
    private JTextField txtSubclasse;
    private JPanel PanelBandDadosPeriodo;
    private JLabel lblDataVencimento;
    private JTextField txtDataVencimento;
    private JLabel lblContaMes;
    private JTextField txtContaMes;
    private JLabel lblValorTotalPagar;
    private JTextField txtValorTotalPagar;
    private JLabel lblConsumoKwhMes;
    private JTextField txtConsumoKwhMes;
    private JLabel lblDataInicioBandeira;
    private JTextField txtDataInicioBandeira;
    private JLabel lblDataFinalBandeira;
    private JTextField txtDataFinalBandeira;
    private JLabel lblTipoBandeira;
    private JTextField txtTipoBandeira;
    private JPanel PanelFaturamento;
    private JLabel lblEmissaoFatura;
    private JTextField txtEmissaoFatura;
    private JLabel lblDiasFatura;
    private JTextField txtDiasFatura;
    private JLabel lblDataLeitAnterior;
    private JTextField txtDataLeitAnterior;
    private JLabel lblDataLeitAtual;
    private JTextField txtDataLeitAtual;
    private JLabel lblDataLeitProxima;
    private JTextField txtDataLeitProxima;
    private JLabel lblLeituraAntKwh;
    private JTextField txtLeituraAntKwh;
    private JLabel lblLeituraAtualKwh;
    private JTextField txtLeituraAtualKwh;
    private JScrollPane jScrollPane1;
    private JTable tblFaturamento;
    private JLabel lblDescricaoFatura;
    private JComboBox<String> cbxDescicaoFatura;
    private JLabel lblValorFornecido;
    private JTextField txtValorFornecido;
    private JLabel lblValorTotalFatura;
    private JTextField txtValorTotalFatura;
    private JButton bntAdd;
    private JButton bntDelete;
    private JLabel lblItensFinanceiros;
    private JLabel lblCIPMunicipal;
    private JTextField txtCIPMunicipal;
    private JLabel lblTributos;
    private JLabel lblPIS;
    private JTextField txtValorPIS;
    private JLabel lblCofins;
    private JTextField txtValorCofins;
    private JLabel lblICMS;
    private JTextField txtValorICMS;
    private JButton btnVoltar;
    private JButton btnLimpar;
    private JButton btnSalvar;
    // End of variables declaration//GEN-END:variables
}
