/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tecsus.ddc.view.frames.energy;

import com.tecsus.ddc.bills.energy.EnergyBill;
import com.tecsus.ddc.controller.service.EnergyBillService;
import com.tecsus.ddc.view.frames.generator.EnergyBillGenerator;
import com.tecsus.ddc.view.frames.home.TelaHome;


/**
 *
 * @author William Antoniazzi
 */
public class Energia extends javax.swing.JInternalFrame {
    private EnergyBillFormTextFields fields;

    private final EnergyBillService energyBillService;

    /**
     * Creates new form Energia
     */
    public Energia(final EnergyBillService energyBillService) {
        fields = new EnergyBillFormTextFields();
        this.energyBillService = energyBillService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrPanelEnergia = new javax.swing.JScrollPane();
        PanelEnergia = new javax.swing.JPanel();
        PanelClienteLocal = new javax.swing.JPanel();
        lblCpfCnpj = new javax.swing.JLabel();
        txtCpfCnpj = new javax.swing.JTextField();
        lblInsEstadual = new javax.swing.JLabel();
        txtInsEstadual = new javax.swing.JTextField();
        lblRazaoSocial = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        lblNomeCliente = new javax.swing.JLabel();
        txtNomeClienteEnd = new javax.swing.JTextField();
        lblVazio01 = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumeroEnd = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplementoEnd = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairroEnd = new javax.swing.JTextField();
        lblCidadeEnd = new javax.swing.JLabel();
        txtCidadeEnd = new javax.swing.JTextField();
        lblCepEnd = new javax.swing.JLabel();
        txtCepEnd = new javax.swing.JTextField();
        lblEstadoEnd = new javax.swing.JLabel();
        cbxEstadoEnd = new javax.swing.JComboBox<>();
        lblVazio02 = new javax.swing.JLabel();
        lblCodIdentificacao = new javax.swing.JLabel();
        txtCodIdentificacao = new javax.swing.JTextField();
        lblCodFiscalOperacao = new javax.swing.JLabel();
        txtCodFiscalOperacao = new javax.swing.JTextField();
        lblGrupoSubgrupo = new javax.swing.JLabel();
        txtGrupoSubgrupo = new javax.swing.JTextField();
        lblClasseSubclasse = new javax.swing.JLabel();
        txtClasseSubclasse = new javax.swing.JTextField();
        lblTipoFornecimento = new javax.swing.JLabel();
        txtTipoFornecimento = new javax.swing.JTextField();
        lblModalidadeTarifa = new javax.swing.JLabel();
        txtModalidadeTarifa = new javax.swing.JTextField();
        lblRoteiroLeitura = new javax.swing.JLabel();
        txtRoteiroLeitura = new javax.swing.JTextField();
        lblTensaoNominal = new javax.swing.JLabel();
        txtTensaoNominal = new javax.swing.JTextField();
        lblNumeroMedidor = new javax.swing.JLabel();
        txtNumeroMedidor = new javax.swing.JTextField();
        lblNumeroInstalacao = new javax.swing.JLabel();
        txtNumeroInstalacao = new javax.swing.JTextField();
        PanelBandDadosPeriodo = new javax.swing.JPanel();
        lblDataVencimento = new javax.swing.JLabel();
        txtDataVencimento = new javax.swing.JTextField();
        lblContaMes = new javax.swing.JLabel();
        txtContaMes = new javax.swing.JTextField();
        lblValorTotalPagar = new javax.swing.JLabel();
        txtValorTotalPagar = new javax.swing.JTextField();
        lblCodigoBarras = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        lblConsumoKwhMes = new javax.swing.JLabel();
        txtConsumoKwhMes = new javax.swing.JTextField();
        lblDataInicioBandeira = new javax.swing.JLabel();
        txtDataInicioBandeira = new javax.swing.JTextField();
        lblDataFinalBandeira = new javax.swing.JLabel();
        txtDataFinalBandeira = new javax.swing.JTextField();
        lblTipoBandeira = new javax.swing.JLabel();
        txtTipoBandeira = new javax.swing.JTextField();
        lblDiasBandeira = new javax.swing.JLabel();
        txtDiasBandeira = new javax.swing.JTextField();
        PanelFaturamento = new javax.swing.JPanel();
        lblEmissaoFatura = new javax.swing.JLabel();
        txtEmissaoFatura = new javax.swing.JTextField();
        lblDiasFatura = new javax.swing.JLabel();
        txtDiasFatura = new javax.swing.JTextField();
        lblDataLeitAnterior = new javax.swing.JLabel();
        txtDataLeitAnterior = new javax.swing.JTextField();
        lblDataLeitAtual = new javax.swing.JLabel();
        txtDataLeitAtual = new javax.swing.JTextField();
        lblDataLeitProxima = new javax.swing.JLabel();
        txtDataLeitProxima = new javax.swing.JTextField();
        lblLeituraAntKwh = new javax.swing.JLabel();
        txtLeituraAntKwh = new javax.swing.JTextField();
        lblLeituraAtualKwh = new javax.swing.JLabel();
        txtLeituraAtualKwh = new javax.swing.JTextField();
        lblCCITusdConsumo = new javax.swing.JLabel();
        lblValorFornTusd = new javax.swing.JLabel();
        txtValorFornTusd = new javax.swing.JTextField();
        lblValorTotalTusd = new javax.swing.JLabel();
        txtValorTotalTusd = new javax.swing.JTextField();
        lblCCITEConsumo = new javax.swing.JLabel();
        lblValorFornTE = new javax.swing.JLabel();
        txtValorFornTE = new javax.swing.JTextField();
        lblValorTotalTE = new javax.swing.JLabel();
        txtValorTotalTE = new javax.swing.JTextField();
        lblItensFinanceiros = new javax.swing.JLabel();
        lblCIPMunicipal = new javax.swing.JLabel();
        txtCIPMunicipal = new javax.swing.JTextField();
        lblTributos = new javax.swing.JLabel();
        lblPIS = new javax.swing.JLabel();
        lblBaseCalculoPIS = new javax.swing.JLabel();
        txtBaseCalculoPIS = new javax.swing.JTextField();
        lblValorPIS = new javax.swing.JLabel();
        txtValorPIS = new javax.swing.JTextField();
        lblCofins = new javax.swing.JLabel();
        lblBaseCalculoCofins = new javax.swing.JLabel();
        txtBaseCalculoCofins = new javax.swing.JTextField();
        lblValorCofins = new javax.swing.JLabel();
        txtValorCofins = new javax.swing.JTextField();
        lblICMS = new javax.swing.JLabel();
        lblBaseCalculoICMS = new javax.swing.JLabel();
        txtBaseCalculoICMS = new javax.swing.JTextField();
        lblValorICMS = new javax.swing.JLabel();
        txtValorICMS = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setTitle("DDC - Sistema de Digitação de Contas");
        setToolTipText("");
//        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tecsus/ddc/view/frames/energy/logoDDCparaIco.png"))); // NOI18N
        setName(""); // NOI18N

        ScrPanelEnergia.setToolTipText("");
        ScrPanelEnergia.setColumnHeaderView(null);

        PanelEnergia.setBorder(javax.swing.BorderFactory.createTitledBorder("CADASTRO DE CONTA DE ENERGIA"));
        PanelEnergia.setToolTipText("");
        PanelEnergia.setName(""); // NOI18N
        PanelEnergia.setOpaque(false);

        PanelClienteLocal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLIENTE / LOCAL CONSUMO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblCpfCnpj.setText("CPF/ CNPJ/ CI:");

        txtCpfCnpj.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCpfCnpj.setToolTipText("");

        lblInsEstadual.setText("Inscrição Estadual:");

        lblRazaoSocial.setText("Razão Social: ");
        lblRazaoSocial.setToolTipText("");

        txtRazaoSocial.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRazaoSocial.setScrollOffset(1);

        lblNomeCliente.setText("Nome Cliente:");

        lblVazio01.setText("   ");

        lblEndereco.setText("Endereço (Rua, Avenida, Estrada...):");

        lblNumero.setText("Número:");

        txtNumeroEnd.setToolTipText("");

        lblComplemento.setText("Complemento:");

        txtComplementoEnd.setToolTipText("");

        lblBairro.setText("Bairro: ");

        txtBairroEnd.setToolTipText("");

        lblCidadeEnd.setText("Cidade:");

        txtCidadeEnd.setToolTipText("");

        lblCepEnd.setText("CEP:");

        txtCepEnd.setToolTipText("");

        lblEstadoEnd.setText("Estado:");

        cbxEstadoEnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblVazio02.setText("   ");

        lblCodIdentificacao.setText("Número da Conta:");

        lblCodFiscalOperacao.setText("Cod. Fiscal Operação:");

        txtCodFiscalOperacao.setToolTipText("");

        lblGrupoSubgrupo.setText("Grupo/ Subgrupo:");
        lblGrupoSubgrupo.setToolTipText("");

        txtGrupoSubgrupo.setToolTipText("");

        lblClasseSubclasse.setText("Classe/ Subclasse:");

        lblTipoFornecimento.setText("Tipo Fornecimento:");

        lblModalidadeTarifa.setText("Modalidade Tarifa:");

        lblRoteiroLeitura.setText("Roteiro de Leitura:");

        lblTensaoNominal.setText("Tensão Nominal:");

        txtTensaoNominal.setToolTipText("");

        lblNumeroMedidor.setText("Número Medidor:");

        lblNumeroInstalacao.setText("Número da Instalação:");

        txtNumeroInstalacao.setToolTipText("");

        javax.swing.GroupLayout PanelClienteLocalLayout = new javax.swing.GroupLayout(PanelClienteLocal);
        PanelClienteLocal.setLayout(PanelClienteLocalLayout);
        PanelClienteLocalLayout.setHorizontalGroup(
            PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                .addComponent(lblNumeroMedidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNumeroMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumeroInstalacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNumeroInstalacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                        .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodIdentificacao)
                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblVazio02))
                            .addComponent(lblTipoFornecimento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                .addComponent(txtTipoFornecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblModalidadeTarifa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtModalidadeTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRoteiroLeitura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRoteiroLeitura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTensaoNominal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTensaoNominal, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                .addComponent(txtCodIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCodFiscalOperacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodFiscalOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblGrupoSubgrupo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGrupoSubgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblClasseSubclasse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtClasseSubclasse))))
                    .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                        .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCpfCnpj)
                            .addComponent(lblInsEstadual)
                            .addComponent(lblVazio01))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                .addComponent(txtInsEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNomeCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeClienteEnd))
                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblRazaoSocial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRazaoSocial))))
                    .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                        .addComponent(lblEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEndereco))
                    .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                        .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumero)
                            .addComponent(lblCidadeEnd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                .addComponent(txtCidadeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCepEnd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCepEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblEstadoEnd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxEstadoEnd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                                .addComponent(txtNumeroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblComplemento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtComplementoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBairroEnd)))))
                .addGap(21, 21, 21))
        );
        PanelClienteLocalLayout.setVerticalGroup(
            PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClienteLocalLayout.createSequentialGroup()
                .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCnpj)
                    .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRazaoSocial)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInsEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNomeCliente)
                        .addComponent(txtNomeClienteEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtInsEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVazio01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumeroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComplemento)
                    .addComponent(txtComplementoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidadeEnd)
                    .addComponent(lblCepEnd)
                    .addComponent(lblEstadoEnd)
                    .addComponent(txtCidadeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCepEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstadoEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVazio02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodIdentificacao)
                    .addComponent(txtCodFiscalOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodFiscalOperacao)
                    .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGrupoSubgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblGrupoSubgrupo)
                        .addComponent(lblClasseSubclasse)
                        .addComponent(txtClasseSubclasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTensaoNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTipoFornecimento)
                        .addComponent(txtTipoFornecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblModalidadeTarifa)
                        .addComponent(txtModalidadeTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRoteiroLeitura)
                        .addComponent(txtRoteiroLeitura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTensaoNominal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelClienteLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroMedidor)
                    .addComponent(txtNumeroMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroInstalacao)
                    .addComponent(txtNumeroInstalacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCpfCnpj.getAccessibleContext().setAccessibleName("txtCpfCnpj");
        lblCodIdentificacao.getAccessibleContext().setAccessibleName("Classe/ Subclasse:");

        PanelBandDadosPeriodo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BANDEIRA / DADOS CONTA / PERÍODO E DESCRIÇÃO CONSUMO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblDataVencimento.setText("Data Vencimento:");

        txtDataVencimento.setToolTipText("");

        lblContaMes.setText("Conta Mês:");

        lblValorTotalPagar.setText("Valor Total Pagar:");

        txtValorTotalPagar.setToolTipText("");

        lblCodigoBarras.setText("Código de Barras:");

        txtCodigoBarras.setToolTipText("");

        lblConsumoKwhMes.setText("Consumo kWh Mês:");

        lblDataInicioBandeira.setText("Data Início Bandeira:");

        lblDataFinalBandeira.setText("Data Final Bandeira:");

        lblTipoBandeira.setText("Tipo Bandeira:");

        lblDiasBandeira.setText("Dias Bandeira:");

        javax.swing.GroupLayout PanelBandDadosPeriodoLayout = new javax.swing.GroupLayout(PanelBandDadosPeriodo);
        PanelBandDadosPeriodo.setLayout(PanelBandDadosPeriodoLayout);
        PanelBandDadosPeriodoLayout.setHorizontalGroup(
            PanelBandDadosPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBandDadosPeriodoLayout.createSequentialGroup()
                .addGroup(PanelBandDadosPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBandDadosPeriodoLayout.createSequentialGroup()
                        .addComponent(lblDataVencimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblContaMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorTotalPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblConsumoKwhMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConsumoKwhMes))
                    .addGroup(PanelBandDadosPeriodoLayout.createSequentialGroup()
                        .addComponent(lblCodigoBarras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigoBarras)))
                .addGap(10, 10, 10))
            .addGroup(PanelBandDadosPeriodoLayout.createSequentialGroup()
                .addComponent(lblDataInicioBandeira)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataInicioBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDataFinalBandeira)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDataFinalBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoBandeira)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTipoBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDiasBandeira)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDiasBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBandDadosPeriodoLayout.setVerticalGroup(
            PanelBandDadosPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBandDadosPeriodoLayout.createSequentialGroup()
                .addGroup(PanelBandDadosPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataVencimento)
                    .addComponent(txtDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContaMes)
                    .addComponent(txtContaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorTotalPagar)
                    .addComponent(txtValorTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsumoKwhMes)
                    .addComponent(txtConsumoKwhMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBandDadosPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoBarras)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBandDadosPeriodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataInicioBandeira)
                    .addComponent(txtDataInicioBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataFinalBandeira)
                    .addComponent(txtDataFinalBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoBandeira)
                    .addComponent(txtTipoBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiasBandeira)
                    .addComponent(txtDiasBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelFaturamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETALHES FATURAMENTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblEmissaoFatura.setText("Emissão Fatura:");

        lblDiasFatura.setText("Dias de Faturamento:");

        lblDataLeitAnterior.setText("Data Leitura Anterior:");

        lblDataLeitAtual.setText("Data Leitura Atual:");

        lblDataLeitProxima.setText("Data Leitura Próxima:");

        lblLeituraAntKwh.setText("Leitura Anterior kWh:");

        lblLeituraAtualKwh.setText("Leitura Atual kWh:");

        lblCCITusdConsumo.setText("CCI - TUSD - Consumo:");

        lblValorFornTusd.setText("Valor Fornecido:");

        lblValorTotalTusd.setText("Valor Total:");

        lblCCITEConsumo.setText("CCI - TE - Consumo:");

        lblValorFornTE.setText("Valor Fornecido:");

        lblValorTotalTE.setText("Valor Total:");

        lblItensFinanceiros.setText("Itens Financeiros:");

        lblCIPMunicipal.setText("CIP - Contribuição Municipal:");

        lblTributos.setText("Tributos:");

        lblPIS.setText("PIS");

        lblBaseCalculoPIS.setText("Base Cálculo:");

        lblValorPIS.setText("Valor (R$):");

        lblCofins.setText("COFINS");

        lblBaseCalculoCofins.setText("Base Cálculo:");

        lblValorCofins.setText("Valor (R$):");

        lblICMS.setText("ICMS");

        lblBaseCalculoICMS.setText("Base Cálculo:");

        lblValorICMS.setText("Valor (R$):");

        javax.swing.GroupLayout PanelFaturamentoLayout = new javax.swing.GroupLayout(PanelFaturamento);
        PanelFaturamento.setLayout(PanelFaturamentoLayout);
        PanelFaturamentoLayout.setHorizontalGroup(
            PanelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                .addGroup(PanelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                        .addComponent(lblEmissaoFatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmissaoFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDiasFatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiasFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDataLeitAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataLeitAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDataLeitAtual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataLeitAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                        .addComponent(lblDataLeitProxima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataLeitProxima, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLeituraAntKwh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLeituraAntKwh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLeituraAtualKwh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLeituraAtualKwh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                        .addComponent(lblCCITusdConsumo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorFornTusd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorFornTusd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorTotalTusd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorTotalTusd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                        .addComponent(lblItensFinanceiros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCIPMunicipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCIPMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                        .addComponent(lblCCITEConsumo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorFornTE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorFornTE, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorTotalTE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorTotalTE, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                        .addComponent(lblTributos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPIS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBaseCalculoPIS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBaseCalculoPIS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorPIS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorPIS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(PanelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                .addComponent(lblICMS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBaseCalculoICMS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBaseCalculoICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValorICMS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                                .addComponent(lblCofins)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblBaseCalculoCofins)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBaseCalculoCofins, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValorCofins)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorCofins, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelFaturamentoLayout.setVerticalGroup(
            PanelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFaturamentoLayout.createSequentialGroup()
                .addGroup(PanelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmissaoFatura)
                    .addComponent(txtEmissaoFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiasFatura)
                    .addComponent(txtDiasFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataLeitAnterior)
                    .addComponent(txtDataLeitAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataLeitAtual)
                    .addComponent(txtDataLeitAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataLeitProxima)
                    .addComponent(txtDataLeitProxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLeituraAntKwh)
                    .addComponent(txtLeituraAntKwh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLeituraAtualKwh)
                    .addComponent(txtLeituraAtualKwh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorFornTusd)
                    .addComponent(txtValorFornTusd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorTotalTusd)
                    .addComponent(txtValorTotalTusd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCCITusdConsumo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorFornTE)
                    .addComponent(txtValorFornTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorTotalTE)
                    .addComponent(txtValorTotalTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCCITEConsumo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCIPMunicipal)
                    .addComponent(txtCIPMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItensFinanceiros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPIS)
                    .addComponent(txtBaseCalculoPIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorPIS)
                    .addComponent(txtValorPIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTributos)
                    .addComponent(lblBaseCalculoPIS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCofins)
                    .addComponent(txtBaseCalculoCofins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorCofins)
                    .addComponent(txtValorCofins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBaseCalculoCofins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblICMS)
                    .addComponent(txtBaseCalculoICMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorICMS)
                    .addComponent(txtValorICMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBaseCalculoICMS))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");

        btnSalvar.setBackground(new java.awt.Color(204, 255, 204));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEnergiaLayout = new javax.swing.GroupLayout(PanelEnergia);
        PanelEnergia.setLayout(PanelEnergiaLayout);
        PanelEnergiaLayout.setHorizontalGroup(
            PanelEnergiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFaturamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelBandDadosPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelClienteLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEnergiaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        PanelEnergiaLayout.setVerticalGroup(
            PanelEnergiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnergiaLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(PanelClienteLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBandDadosPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelFaturamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEnergiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnLimpar)
                    .addComponent(btnSalvar))
                .addContainerGap())
        );

        ScrPanelEnergia.setViewportView(PanelEnergia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrPanelEnergia)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrPanelEnergia, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       energyBillService.insert(EnergyBillGenerator.generate(fields));

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        TelaHome.energyFrameisNotOpened = true;
// TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBandDadosPeriodo;
    private javax.swing.JPanel PanelClienteLocal;
    private javax.swing.JPanel PanelEnergia;
    private javax.swing.JPanel PanelFaturamento;
    private javax.swing.JScrollPane ScrPanelEnergia;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxEstadoEnd;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblBaseCalculoCofins;
    private javax.swing.JLabel lblBaseCalculoICMS;
    private javax.swing.JLabel lblBaseCalculoPIS;
    private javax.swing.JLabel lblCCITEConsumo;
    private javax.swing.JLabel lblCCITusdConsumo;
    private javax.swing.JLabel lblCIPMunicipal;
    private javax.swing.JLabel lblCepEnd;
    private javax.swing.JLabel lblCidadeEnd;
    private javax.swing.JLabel lblClasseSubclasse;
    private javax.swing.JLabel lblCodFiscalOperacao;
    private javax.swing.JLabel lblCodIdentificacao;
    private javax.swing.JLabel lblCodigoBarras;
    private javax.swing.JLabel lblCofins;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblConsumoKwhMes;
    private javax.swing.JLabel lblContaMes;
    private javax.swing.JLabel lblCpfCnpj;
    private javax.swing.JLabel lblDataFinalBandeira;
    private javax.swing.JLabel lblDataInicioBandeira;
    private javax.swing.JLabel lblDataLeitAnterior;
    private javax.swing.JLabel lblDataLeitAtual;
    private javax.swing.JLabel lblDataLeitProxima;
    private javax.swing.JLabel lblDataVencimento;
    private javax.swing.JLabel lblDiasBandeira;
    private javax.swing.JLabel lblDiasFatura;
    private javax.swing.JLabel lblEmissaoFatura;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstadoEnd;
    private javax.swing.JLabel lblGrupoSubgrupo;
    private javax.swing.JLabel lblICMS;
    private javax.swing.JLabel lblInsEstadual;
    private javax.swing.JLabel lblItensFinanceiros;
    private javax.swing.JLabel lblLeituraAntKwh;
    private javax.swing.JLabel lblLeituraAtualKwh;
    private javax.swing.JLabel lblModalidadeTarifa;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumeroInstalacao;
    private javax.swing.JLabel lblNumeroMedidor;
    private javax.swing.JLabel lblPIS;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblRoteiroLeitura;
    private javax.swing.JLabel lblTensaoNominal;
    private javax.swing.JLabel lblTipoBandeira;
    private javax.swing.JLabel lblTipoFornecimento;
    private javax.swing.JLabel lblTributos;
    private javax.swing.JLabel lblValorCofins;
    private javax.swing.JLabel lblValorFornTE;
    private javax.swing.JLabel lblValorFornTusd;
    private javax.swing.JLabel lblValorICMS;
    private javax.swing.JLabel lblValorPIS;
    private javax.swing.JLabel lblValorTotalPagar;
    private javax.swing.JLabel lblValorTotalTE;
    private javax.swing.JLabel lblValorTotalTusd;
    private javax.swing.JLabel lblVazio01;
    private javax.swing.JLabel lblVazio02;
    private javax.swing.JTextField txtBairroEnd;
    private javax.swing.JTextField txtBaseCalculoCofins;
    private javax.swing.JTextField txtBaseCalculoICMS;
    private javax.swing.JTextField txtBaseCalculoPIS;
    private javax.swing.JTextField txtCIPMunicipal;
    private javax.swing.JTextField txtCepEnd;
    private javax.swing.JTextField txtCidadeEnd;
    private javax.swing.JTextField txtClasseSubclasse;
    private javax.swing.JTextField txtCodFiscalOperacao;
    private javax.swing.JTextField txtCodIdentificacao;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtComplementoEnd;
    private javax.swing.JTextField txtConsumoKwhMes;
    private javax.swing.JTextField txtContaMes;
    private javax.swing.JTextField txtCpfCnpj;
    private javax.swing.JTextField txtDataFinalBandeira;
    private javax.swing.JTextField txtDataInicioBandeira;
    private javax.swing.JTextField txtDataLeitAnterior;
    private javax.swing.JTextField txtDataLeitAtual;
    private javax.swing.JTextField txtDataLeitProxima;
    private javax.swing.JTextField txtDataVencimento;
    private javax.swing.JTextField txtDiasBandeira;
    private javax.swing.JTextField txtDiasFatura;
    private javax.swing.JTextField txtEmissaoFatura;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtGrupoSubgrupo;
    private javax.swing.JTextField txtInsEstadual;
    private javax.swing.JTextField txtLeituraAntKwh;
    private javax.swing.JTextField txtLeituraAtualKwh;
    private javax.swing.JTextField txtModalidadeTarifa;
    private javax.swing.JTextField txtNomeClienteEnd;
    private javax.swing.JTextField txtNumeroEnd;
    private javax.swing.JTextField txtNumeroInstalacao;
    private javax.swing.JTextField txtNumeroMedidor;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtRoteiroLeitura;
    private javax.swing.JTextField txtTensaoNominal;
    private javax.swing.JTextField txtTipoBandeira;
    private javax.swing.JTextField txtTipoFornecimento;
    private javax.swing.JTextField txtValorCofins;
    private javax.swing.JTextField txtValorFornTE;
    private javax.swing.JTextField txtValorFornTusd;
    private javax.swing.JTextField txtValorICMS;
    private javax.swing.JTextField txtValorPIS;
    private javax.swing.JTextField txtValorTotalPagar;
    private javax.swing.JTextField txtValorTotalTE;
    private javax.swing.JTextField txtValorTotalTusd;
    // End of variables declaration//GEN-END:variables
}
